name: workflow

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    name: "Deployment"
    runs-on: "ubuntu-latest"
    steps:
     - name: Check out the repo
       uses: actions/checkout@v2

     - name: Set Relase version
       id: vars
       run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
       
     - name: Configure AWS credential
       uses: aws-actions/configure-aws-credentials@v1
       with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1
 
     - name: Build, tag, and push image to Amazon ECRs
       id: build-image
       env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: strapiapp
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
       run: |
          echo $IMAGE_TAG
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          
     - name: Check tag version
       run: | 
           echo $RELEASE_VERSION
           echo ${{ env.RELEASE_VERSION }}
           echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
           echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
     - name: terraform initialization 
       run: cd strapi-terraform/ && terraform init -var="tag=${{ env.RELEASE_VERSION }}

     - name: Terraform validation
       run: cd strapi-terraform/ && terraform validate
       
     - name: terraform deployment
       run: cd strapi-terraform/ && terraform apply -var="tag=${{ env.RELEASE_VERSION }}"  -auto-approve